version: "3"

services:
  inbound-api:
    container_name: e-commerce-api-inbound-prod
    command: yarn start

  interface-api:
    container_name: e-commerce-api-interface-prod
    build:
      target: production
    command: yarn start
