version: "3"

services:
  inbound-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    image: e-commerce-api
    environment:
      - MONGODB_URL=mongodb://mongo:27017/node-boilerplate
      - CLIENT_URL=${CLIENT_URL}
    links:
      - mongo
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - backend

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
